CREATURE_ABILITY_ADDON_NAMES = [
    "Frequency",
    "Trigger",
    "Effect",
    "Duration",
    "Requirement",
    "Requirements",
    "Prerequisite",
    "Critical Success",
    "Success",
    "Failure",
    "Critical Failure",
    "Range",
    "Cost",
]

CREATURE_ABILITY_ADDON_KEYS = [
    "frequency",
    "trigger",
    "effect",
    "duration",
    "requirement",
    "critical success",
    "success",
    "failure",
    "critical failure",
]

CREATURE_SPANS_ALLOWED = [
    "Adult Black Dragon",
    "Adult Blue Dragon",
    "Adult Brass Dragon",
    "Adult Bronze Dragon",
    "Adult Copper Dragon",
    "Adult Forest Dragon",
    "Adult Gold Dragon",
    "Adult Green Dragon",
    "Adult Red Dragon",
    "Adult Sea Dragon",
    "Adult Silver Dragon",
    "Adult Sky Dragon",
    "Adult Sovereign Dragon",
    "Adult Underworld Dragon",
    "Adult White Dragon",
    "Ancient Black Dragon",
    "Ancient Blue Dragon",
    "Ancient Brass Dragon",
    "Ancient Bronze Dragon",
    "Ancient Copper Dragon",
    "Ancient Forest Dragon",
    "Ancient Gold Dragon",
    "Ancient Green Dragon",
    "Ancient Red Dragon",
    "Ancient Sea Dragon",
    "Ancient Silver Dragon",
    "Ancient Sky Dragon",
    "Ancient Sovereign Dragon",
    "Ancient Underworld Dragon",
    "Ancient White Dragon",
    "Arboreal Snag",
    "Avalanche Legion",
    "Barnacle Ghoul",
    "Beetle Carapace",
    "Blackfrost Guecubu",
    "Blackfrost Prophet",
    "Blackfrost Zombie",
    "Blizzardborn",
    "Blodeuwedd",
    "Blustering Gale",
    "Boiling Spring",
    "Brine Shark",
    "Chimpanzee Visitant",
    "City Guard Squadron",
    "Clockwork Fabricator",
    "Clockwork Shambler Horde",
    "Coldmire Pond",
    "Cultist Troop",
    "Dancing Night Parade",
    "Daqqanoenyent",
    "Darivan",
    "Demilich",
    "Demonic Rabble",
    "Dewdrop Jelly",
    "Dirge Piper",
    "Drake Skeleton",
    "Dryad Queen",
    "Dryad",
    "Elemental Tsunami",
    "Elemental Vessel, Water",
    "Fabled Harrowkin",
    "Festering Gnasher",
    "Ghast",
    "Ghost Commoner",
    "Ghost Mage",
    "Ghost Pirate Captain",
    "Ghostly Mob",
    "Ghoul Antipaladin",
    "Ghoul Gnawer",
    "Ghoul Razorclaw",
    "Ghoul",
    "Giant Seahorse",
    "Gold Defender Garrison",
    "Graveknight Captain",
    "Graveknight Champion",
    "Graveknight Warmaster",
    "Graveknight",
    "Greater Barghest",
    "Greater Shadow",
    "Hana's Hundreds",
    "Hadi Mob",
    "Harlo Krant",
    "Harvest Regiment",
    "Harpy Skeleton",
    "Hellknight Cavalry Brigade",
    "Hesperid Queen",
    "Hesperid",
    "Horde Lich",
    "Hryngar Breccia Squad",
    "Hungry Ghost",
    "Husk Zombie",
    "Icewyrm",
    "Icicle Snake",
    "Jitterbone Contortionist",
    "Kothogaz, Dance Of Disharmony",
    "Kuworsys",
    "Lacedon",
    "Lampad Queen",
    "Lampad",
    "Last Guard",
    "Ledalusca",
    "Leng Ghoul",
    "Lich",
    "Lion Visitant",
    "Living Waterfall",
    "Mechanical Carny",
    "Melfesh Monster",
    "Minister Of Tumult",
    "Mist Stalker",
    "Mosquito Witch",
    "Mutant Desert Drake",
    "Mutant Giant Toad",
    "Mutant Gnoll Hulk",
    "Naiad Queen",
    "Naiad",
    "Nanoshard Swarm",
    "Necromancer Troop",
    "Nightmarchers",
    "Nornhound",
    "Nosferatu Malefactor",
    "Nosferatu Overlord",
    "Nosferatu Thrall",
    "Oaksteward Enforcer",
    "Oil Living Graffiti",
    "Pelegox Cube",
    "Petitioner",
    "Plague Zombie",
    "Planar Terra-Cotta Squadron",
    "Priest of Kabriri",
    "Provincial Jiang-Shi",
    "Quatoid",
    "Rancorous Priesthood",
    "Ravener Husk",
    "Ravener",
    "Runecarved Lich",
    "Saltborn Stalkers",
    "Shadow",
    "Shadowbound Monk Statue",
    "Shambler Troop",
    "Simple Harrowkin",
    "Shock Zombie",
    "Sinspawn",
    "Skeletal Champion",
    "Skeletal Giant",
    "Skeletal Horse",
    "Skeletal Hulk",
    "Skeletal Mage",
    "Skeletal Soldier",
    "Skeletal Titan",
    "Skeleton Guard",
    "Skeleton Infantry",
    "Sootsoldiers",
    "Soul Swarm",
    "Spellskein",
    "Spring-Heeled Jack",
    "Stone Lion",
    "Stone Lion Cub",
    "Stone Spider",
    "Storied Harrowkin",
    "Strigoi Progenitor",
    "Sulfur Zombie",
    "Summer Hora Queen",
    "Summer Hora",
    "Sun Warrior Brigade",
    "Taljjae",
    "Tar Zombie Mammoth",
    "Tar Zombie Predator",
    "Tar Zombie Snatcher",
    "Taunting Skull",
    "Tehialai-Thief-Of-Ships",
    "Terra-Cotta Garrison",
    "Tidal Master",
    "Tyrannosaurus Skeleton",
    "Ulgrem-Axaan",
    "Vampire Count",
    "Vampire Guardian",
    "Vampire Mastermind",
    "Vampire Spawn",
    "Vetalarana Emergent",
    "Vetalarana Manipulator",
    "Virulak Necromancer",
    "Virulak Villager",
    "Vrykolakas Ancient",
    "Vrykolakas Master",
    "Vrykolakas Spawn",
    "Volodmyra",
    "Waldgeist",
    "Werebat",
    "Werebear",
    "Wereboar",
    "Werecrocodile",
    "Wererat",
    "Weretiger",
    "Werewolf",
    "Withered",
    "Wolf Skeleton",
    "Worm That Walks Cultist",
    "Wrath Riot",
    "Young Black Dragon",
    "Young Blue Dragon",
    "Young Brass Dragon",
    "Young Bronze Dragon",
    "Young Copper Dragon",
    "Young Forest Dragon",
    "Young Gold Dragon",
    "Young Green Dragon",
    "Young Red Dragon",
    "Young Sea Dragon",
    "Young Silver Dragon",
    "Young Sky Dragon",
    "Young Sovereign Dragon",
    "Young Underworld Dragon",
    "Young White Dragon",
    "Xulgath Ravening",
    "Zombie Brute",
    "Zombie Dragon",
    "Zombie Hulk",
    "Zombie Lord",
    "Zombie Mammoth",
    "Zombie Owlbear",
    "Zombie Shambler",
    "Zombie Snake",
]
