CREATURE_ABILITY_ADDON_NAMES = [
    "Frequency",
    "Trigger",
    "Effect",
    "Duration",
    "Requirement",
    "Requirements",
    "Prerequisite",
    "Critical Success",
    "Success",
    "Failure",
    "Critical Failure",
    "Range",
    "Cost",
]

CREATURE_ABILITY_ADDON_KEYS = [
    "frequency",
    "trigger",
    "effect",
    "duration",
    "requirement",
    "critical success",
    "success",
    "failure",
    "critical failure",
]

CREATURE_NOT_SPELLS = [
    "Soul Spells",
    "Signature Spells",
    "Green Rituals",
    "Dead Spells",
    "Distracting Spells",
]

CREATURE_SPANS_ALLOWED = [
    "Adamantine Archdragon",
    "Adult Adamantine Dragon",
    "Adult Black Dragon",
    "Adult Blue Dragon",
    "Adult Brass Dragon",
    "Adult Bronze Dragon",
    "Adult Cinder Dragon",
    "Adult Conspirator Dragon",
    "Adult Coral Dragon",
    "Adult Copper Dragon",
    "Adult Despair Dragon",
    "Adult Diabolic Dragon",
    "Adult Empyreal Dragon",
    "Adult Forest Dragon",
    "Adult Fortune Dragon",
    "Adult Gold Dragon",
    "Adult Green Dragon",
    "Adult Horned Dragon",
    "Adult Mirage Dragon",
    "Adult Omen Dragon",
    "Adult Phase Dragon",
    "Adult Red Dragon",
    "Adult Requiem Dragon",
    "Adult Resurrection Dragon",
    "Adult Rune Dragon",
    "Adult Sea Dragon",
    "Adult Silver Dragon",
    "Adult Sky Dragon",
    "Adult Sovereign Dragon",
    "Adult Underworld Dragon",
    "Adult Whisper Dragon",
    "Adult White Dragon",
    "Ancient Adamantine Dragon",
    "Ancient Black Dragon",
    "Ancient Blue Dragon",
    "Ancient Brass Dragon",
    "Ancient Bronze Dragon",
    "Ancient Cinder Dragon",
    "Ancient Conspirator Dragon",
    "Ancient Coral Dragon",
    "Ancient Copper Dragon",
    "Ancient Despair Dragon",
    "Ancient Diabolic Dragon",
    "Ancient Empyreal Dragon",
    "Ancient Forest Dragon",
    "Ancient Fortune Dragon",
    "Ancient Gold Dragon",
    "Ancient Green Dragon",
    "Ancient Horned Dragon",
    "Ancient Mirage Dragon",
    "Ancient Omen Dragon",
    "Ancient Phase Dragon",
    "Ancient Red Dragon",
    "Ancient Requiem Dragon",
    "Ancient Resurrection Dragon",
    "Ancient Rune Dragon",
    "Ancient Sea Dragon",
    "Ancient Silver Dragon",
    "Ancient Sky Dragon",
    "Ancient Sovereign Dragon",
    "Ancient Underworld Dragon",
    "Ancient Whisper Dragon",
    "Ancient White Dragon",
    "Angelic Chorus",
    "Apprentice Magician Clique",
    "Arboreal Copse",
    "Arboreal Snag",
    "Archer Regiment",
    "Archon Bastion",
    "Arrester Squadron",
    "Aurochs Herd",
    "Avalanche Legion",
    "Bandit Gang",
    "Beiran Frosthunt",
    "Barnacle Ghoul",
    "Boggard Dreadknot",
    "Batkin Guard",
    "Beetle Carapace",
    "Besieged Logging Crew",
    "Bill-Band",
    "Black Belt",
    "Blackfrost Guecubu",
    "Blackfrost Prophet",
    "Blackfrost Zombie",
    "Blizzardborn",
    "Blodeuwedd",
    "Blustering Gale",
    "Boggard Scouting Party",
    "Boiling Spring",
    "Brine Shark",
    "Cacodaemon",
    "Cassisian",
    "Charau-Ka Shrieker Crew",
    "Chimera",
    "Chimpanzee Visitant",
    "Cinder Archdragon",
    "City Guard Squadron",
    "Clockwork Dragon",
    "Clockwork Fabricator",
    "Clockwork Infantry",
    "Clockwork Mage",
    "Clockwork Runner Pack",
    "Clockwork Shambler Horde",
    "Clockwork Soldier",
    "Clockwork Spy",
    "Coldmire Pond",
    "Combat Engineer",
    "Conscript Squad",
    "Conspirator Archdragon",
    "Coral Archdragon",
    "Corn Leshy Throng",
    "Cultist Troop",
    "Dancing Night Parade",
    "Daqqanoenyent",
    "Darivan",
    "Deathless Pirate",
    "Dezullon Thicket",
    "Deinonychus Pack",
    "Deluded Mob",
    "Demilich",
    "Demonic Rabble",
    "Despair Archdragon",
    "Diabolic Archdragon",
    "Dewdrop Jelly",
    "Dirge Piper",
    "Drake Flight",
    "Drake Skeleton",
    "Drill Sergeant",
    "Druid Circle",
    "Dromaar Company",
    "Dryad Queen",
    "Dryad",
    "Dwarf Battalion",
    "Dwarf Longshot Squad",
    "Einherji Host",
    "Elemental Tsunami",
    "Elemental Vessel, Water",
    "Empyreal Archdragon",
    "Fabled Harrowkin",
    "Failed Prophet",
    "Festering Gnasher",
    "First-Class Infantry",
    "Fleshwarp Amalgam",
    "Floodslain Orc",
    "Fortune Archdragon",
    "Gadgeteer",
    "Gale Frenzy",
    "Gargoyle Wing",
    "Ghast",
    "Ghost Commoner",
    "Ghost Mage",
    "Ghost Pirate Captain",
    "Ghostly Mob",
    "Ghoul Antipaladin",
    "Ghoul Gnawer",
    "Ghoul Razorclaw",
    "Ghoul Soldier",
    "Ghoul Stalker",
    "Ghoul",
    "Giant Ant Army",
    "Giant Seahorse",
    "Gnome Cannon Corps",
    "Goblin Get Gang",
    "Goblin Rabble",
    "God Caller",
    "Gold Defender Garrison",
    "Gorumite Infantry",
    "Grandmaster",
    "Graveknight Captain",
    "Graveknight Champion",
    "Graveknight Warmaster",
    "Graveknight",
    "Greater Barghest",
    "Greater Chimera",
    "Greater Shadow",
    "Hadi Mob",
    "Halfling Lucky Draw",
    "Hana's Hundreds",
    "Harlo Krant",
    "Harpy Skeleton",
    "Harvest Regiment",
    "Heavy Cavalry",
    "Hell Hound Pack",
    "Hellknight Cavalry Brigade",
    "Hesperid Queen",
    "Hesperid",
    "Hobgoblin Battalion",
    "Hobgoblin Veteran Regiment",
    "Horde Lich",
    "Horned Archdragon",
    "Hryngar Breccia Squad",
    "Hungry Ghost",
    "Husk Zombie",
    "Icewyrm",
    "Icicle Snake",
    "Infantry Soldier",
    "Jitterbone Contortionist",
    "Kandirvek",
    "Lady Siccale",
    "Seldeg Bhedlis (Claws of the Tyrant)",
    "Kobold Trap Squad",
    "Kothogaz, Dance Of Disharmony",
    "Kuworsys",
    "Lacedon",
    "Lampad Queen",
    "Lampad",
    "Last Guard",
    "Ledalusca",
    "Leng Ghoul",
    "Leshy Mob",
    "Animated Army",
    "Leukodaemon Plague",
    "Lich",
    "Lich Legion",
    "Line Infantry",
    "Lion Visitant",
    "Living Waterfall",
    "Mage Knight",
    "Manticore",
    "Martial Student",
    "Mask of Norgorber",
    "Mechanical Carny",
    "Melfesh Monster",
    "Mercenary Band",
    "Minister Of Tumult",
    "Mirage Archdragon",
    "Mist Stalker",
    "Mitflit Vermin Cavalry",
    "Mixed Martial Artist",
    "Monk Cadre",
    "Monster Hunter",
    "Mosquito Witch",
    "Mutant Desert Drake",
    "Mutant Giant Toad",
    "Mutant Gnoll Hulk",
    "Naiad Queen",
    "Naiad",
    "Nanoshard Swarm",
    "Necromancer Troop",
    "Nightmarchers",
    "Noppera-Bo Impersonator",
    "Nornhound",
    "Nosferatu Malefactor",
    "Nosferatu Overlord",
    "Nosferatu Thrall",
    "Oaksteward Enforcer",
    "Ofalth Stampede",
    "Oil Living Graffiti",
    "Omelia",
    "Omen Archdragon",
    "Omox Slime Pool",
    "Orc Raiding Party",
    "Orc Skullcrushers",
    "Ordulf Bladecaller",
    "Ossuary Warden",
    "Paleohemoth",
    "Path Maiden",
    "Pelegox Cube",
    "Petitioner",
    "Phalanx Formation",
    "Phase Archdragon",
    "Plague Zombie",
    "Planar Terra-Cotta Squadron",
    "Priest of Kabriri",
    "Provincial Jiang-Shi",
    "Protean Tumult",
    "Qadiran Camel Corps",
    "Quatoid",
    "Raised Cavalry",
    "Rancorous Priesthood",
    "Ratfolk Shank Squad",
    "Ravener Husk",
    "Ravener",
    "Redcap Brigade",
    "Requiem Archdragon",
    "Resurrection Archdragon",
    "Rune Archdragon",
    "Runecarved Lich",
    "Ruzadoya's Chosen",
    "Saltborn Stalkers",
    "Scamp Inferno",
    "Sea Archdragon",
    "Shade",
    "Shadow",
    "Shadowbound Monk Statue",
    "Shambler Troop",
    "Shock Zombie",
    "Simple Harrowkin",
    "Sinswarm",
    "Sinspawn",
    "Skeletal Champion",
    "Skeletal Giant",
    "Skeletal Horse",
    "Skeletal Hulk",
    "Skeletal Mage",
    "Skeletal Rat Swarm",
    "Skeletal Soldier",
    "Skeletal Titan",
    "Skeleton Guard",
    "Skeleton Infantry",
    "Skeleton Mob",
    "Skittering Slayer",
    "Sniper",
    "Sootsoldiers",
    "Soul Swarm",
    "Spawning Soulrider",
    "Speiroikos",
    "Spellskein",
    "Spring-Heeled Jack",
    "Standard Bearer",
    "Stone Bulwark",
    "Stone Lion Cub",
    "Stone Lion",
    "Stone Spider",
    "Storied Harrowkin",
    "Strigoi Progenitor",
    "Strigoi Servant",
    "Sulfur Zombie",
    "Summer Hora Queen",
    "Summer Hora",
    "Sun Warrior Brigade",
    "Swamp Blight",
    "Sylirican Phalanx",
    "Taljjae",
    "Tar Zombie Mammoth",
    "Tar Zombie Predator",
    "Tar Zombie Snatcher",
    "Taunting Skull",
    "Tehialai-Thief-Of-Ships",
    "Terra-Cotta Garrison",
    "The Great Flood",
    "Thousand Thieves",
    "Tidal Master",
    "Tournament Combatant",
    "Tyrannosaurus Skeleton",
    "Ulgrem-Axaan",
    "Undead Murder",
    "Valkyrie Tempest",
    "Vampire Count",
    "Vampire Guardian",
    "Vampire Mastermind",
    "Vampire Servant",
    "Vampire Servitor",
    "Vampire Spawn",
    "Vanth Guardian Flock",
    "Velociraptor Pack",
    "Vetalarana Emergent",
    "Vetalarana Manipulator",
    "Viking Guard",
    "Virulak Necromancer",
    "Virulak Villager",
    "Volodmyra",
    "Vordine Legion",
    "Vrykolakas Ancient",
    "Vrykolakas Master",
    "Vrykolakas Spawn",
    "Waldgeist",
    "Watchmage Squadron",
    "Werebat Warrior",
    "Werebat",
    "Werebear",
    "Wereboar",
    "Werecrocodile",
    "Weremoose",
    "Wererat",
    "Wereshark",
    "Weretiger",
    "Werewolf",
    "Whisper Archdragon",
    "Wight Battalion",
    "Withered",
    "Wolf Pack",
    "Wolf Skeleton",
    "Woodland Scouts",
    "Worm Prophet",
    "Worm That Walks Cultist",
    "Wrath Riot",
    "Xulgath Army",
    "Xulgath Dinosaur Cavalry",
    "Xulgath Ravening",
    "Young Adamantine Dragon",
    "Young Black Dragon",
    "Young Blue Dragon",
    "Young Brass Dragon",
    "Young Bronze Dragon",
    "Young Cinder Dragon",
    "Young Conspirator Dragon",
    "Young Copper Dragon",
    "Young Coral Dragon",
    "Young Despair Dragon",
    "Young Diabolic Dragon",
    "Young Empyreal Dragon",
    "Young Forest Dragon",
    "Young Fortune Dragon",
    "Young Gold Dragon",
    "Young Green Dragon",
    "Young Horned Dragon",
    "Young Mirage Dragon",
    "Young Omen Dragon",
    "Young Phase Dragon",
    "Young Red Dragon",
    "Young Requiem Dragon",
    "Young Resurrection Dragon",
    "Young Rune Dragon",
    "Young Sea Dragon",
    "Young Silver Dragon",
    "Young Sky Dragon",
    "Young Sovereign Dragon",
    "Young Underworld Dragon",
    "Young Whisper Dragon",
    "Young White Dragon",
    "Zecui Horde",
    "Zombie Bear",
    "Zombie Brute",
    "Zombie Desecrator",
    "Zombie Dragon",
    "Zombie Hulk",
    "Zombie Lord",
    "Zombie Mammoth",
    "Zombie Owlbear",
    "Zombie Shambler",
    "Zombie Snake",
]

CREATURE_UL_ALLOWED = [
    "Archer Regiment",
    "First-Class Infantry",
    "Vampire Servant",
]

CREATURE_TABLE_ALLOWED = [
    "Failed Prophet",
]

CREATURE_IGNORE_DC_AURA = [
    "Island Oni",
    "Primal Warden of Zibik",
    "Courtesan",
    "Loan Shark",
    "Tempest Incarnate",
]

# Creatures with non-standard links (using URL parameters instead of game-obj attributes)
# These links can't be extracted as structured link objects, so we allow them in markdown
CREATURE_LINKS_ALLOWED = [
    "Scarecophagus",
    "Talos Gadgeteer",
]

CREATURE_ATTRIBUTES = ["str", "dex", "con", "int", "wis", "cha"]

KINGDOM_ATTRIBUTES = [
    "culture",
    "economy",
    "loyalty",
    "stability",
]

ORC_LICENSE = {
    "name": "ORC Notice",
    "type": "section",
    "sections": [
        {
            "name": "Attribution",
            "type": "section",
            "text": "This product is based on the following Licensed Material:",
            "sections": [],
        },
        {
            "name": "Attributing us",
            "type": "section",
            "text": "If you use our Licensed Material in your own published works, please credit us as follows:",
            "sections": [
                {
                    "name": "Pathfinder Open Reference",
                    "type": "section",
                    "text": "© 2023 Masterwork Tools LLC, Authors: Devon Jones, Monica Jones.",
                }
            ],
        },
        {
            "name": "Reserved Material",
            "type": "section",
            "text": "Reserved Material elements in this product include, but may not be limited to: [none]",
        },
        {
            "name": "Expressly Designated Licensed Material",
            "type": "section",
            "text": "The following elements are owned by the Licensor and would otherwise constitute Reserved Material and are hereby designated as Licensed Material: [None].",
        },
    ],
    "subtype": "license",
    "license": "Open RPG Creative license",
    "text": "This product is licensed under the ORC License to be held in the Library of Congress and available online at various locations including paizo.com/orclicense, azoralaw.com/orclicense, and others. All warranties are disclaimed as set forth therein.",
}
