CREATURE_ABILITY_ADDON_NAMES = [
    "Frequency",
    "Trigger",
    "Effect",
    "Duration",
    "Requirement",
    "Requirements",
    "Prerequisite",
    "Critical Success",
    "Success",
    "Failure",
    "Critical Failure",
    "Range",
    "Cost",
]

CREATURE_ABILITY_ADDON_KEYS = [
    "frequency",
    "trigger",
    "effect",
    "duration",
    "requirement",
    "critical success",
    "success",
    "failure",
    "critical failure",
]

CREATURE_NOT_SPELLS = [
    "Soul Spells",
    "Signature Spells",
    "Green Rituals",
    "Dead Spells",
    "Distracting Spells"
]

CREATURE_SPANS_ALLOWED = [
    "Adult Black Dragon",
    "Adult Blue Dragon",
    "Adult Brass Dragon",
    "Adult Bronze Dragon",
    "Adult Copper Dragon",
    "Adult Forest Dragon",
    "Adult Gold Dragon",
    "Adult Green Dragon",
    "Adult Red Dragon",
    "Adult Sea Dragon",
    "Adult Silver Dragon",
    "Adult Sky Dragon",
    "Adult Sovereign Dragon",
    "Adult Underworld Dragon",
    "Adult White Dragon",
    "Ancient Black Dragon",
    "Ancient Blue Dragon",
    "Ancient Brass Dragon",
    "Ancient Bronze Dragon",
    "Ancient Copper Dragon",
    "Ancient Forest Dragon",
    "Ancient Gold Dragon",
    "Ancient Green Dragon",
    "Ancient Red Dragon",
    "Ancient Sea Dragon",
    "Ancient Silver Dragon",
    "Ancient Sky Dragon",
    "Ancient Sovereign Dragon",
    "Ancient Underworld Dragon",
    "Ancient White Dragon",
    "Arboreal Snag",
    "Arrester Squadron",
    "Aurochs Herd",
    "Avalanche Legion",
    "Bandit Gang",
    "Barnacle Ghoul",
    "Beetle Carapace",
    "Besieged Logging Crew",
    "Bill-Band",
    "Black Belt",
    "Blackfrost Guecubu",
    "Blackfrost Prophet",
    "Blackfrost Zombie",
    "Blizzardborn",
    "Blodeuwedd",
    "Blustering Gale",
    "Boiling Spring",
    "Brine Shark",
    "Cacodaemon",
    "Cassisian",
    "Chimera",
    "Chimpanzee Visitant",
    "City Guard Squadron",
    "Clockwork Fabricator",
    "Clockwork Shambler Horde",
    "Coldmire Pond",
    "Combat Engineer",
    "Conscript Squad",
    "Corn Leshy Throng",
    "Cultist Troop",
    "Dancing Night Parade",
    "Daqqanoenyent",
    "Darivan",
    "Deluded Mob",
    "Demilich",
    "Demonic Rabble",
    "Dewdrop Jelly",
    "Dirge Piper",
    "Drake Skeleton",
    "Drill Sergeant",
    "Dryad Queen",
    "Dryad",
    "Dwarf Battalion",
    "Einherji Host",
    "Elemental Tsunami",
    "Elemental Vessel, Water",
    "Fabled Harrowkin",
    "Festering Gnasher",
    "Floodslain Orc",
    "Gadgeteer",
    "Ghast",
    "Ghost Commoner",
    "Ghost Mage",
    "Ghost Pirate Captain",
    "Ghostly Mob",
    "Ghoul Antipaladin",
    "Ghoul Gnawer",
    "Ghoul Razorclaw",
    "Ghoul Soldier",
    "Ghoul Stalker",
    "Ghoul",
    "Giant Seahorse",
    "Goblin Get Gang",
    "God Caller",
    "Gold Defender Garrison",
    "Gorumite Infantry",
    "Grandmaster",
    "Graveknight Captain",
    "Graveknight Champion",
    "Graveknight Warmaster",
    "Graveknight",
    "Greater Barghest",
    "Greater Chimera",
    "Greater Shadow",
    "Hana's Hundreds",
    "Hadi Mob",
    "Harlo Krant",
    "Harvest Regiment",
    "Harpy Skeleton",
    "Heavy Cavalry",
    "Hellknight Cavalry Brigade",
    "Hesperid Queen",
    "Hesperid",
    "Hobgoblin Battalion",
    "Horde Lich",
    "Hryngar Breccia Squad",
    "Hungry Ghost",
    "Husk Zombie",
    "Icewyrm",
    "Icicle Snake",
    "Infantry Soldier",
    "Jitterbone Contortionist",
    "Kothogaz, Dance Of Disharmony",
    "Kuworsys",
    "Lacedon",
    "Lampad Queen",
    "Lampad",
    "Last Guard",
    "Ledalusca",
    "Leng Ghoul",
    "Leshy Mob",
    "Lich",
    "Line Infantry",
    "Lion Visitant",
    "Living Waterfall",
    "Mage Knight",
    "Manticore",
    "Martial Student",
    "Mask of Norgorber",
    "Mechanical Carny",
    "Mercenary Band",
    "Melfesh Monster",
    "Minister Of Tumult",
    "Mist Stalker",
    "Mixed Martial Artist",
    "Monster Hunter",
    "Mosquito Witch",
    "Mutant Desert Drake",
    "Mutant Giant Toad",
    "Mutant Gnoll Hulk",
    "Naiad Queen",
    "Naiad",
    "Nanoshard Swarm",
    "Necromancer Troop",
    "Nightmarchers",
    "Noppera-Bo Impersonator",
    "Nornhound",
    "Nosferatu Malefactor",
    "Nosferatu Overlord",
    "Nosferatu Thrall",
    "Oaksteward Enforcer",
    "Oil Living Graffiti",
    "Orc Skullcrushers",
    "Ordulf Bladecaller",
    "Paleohemoth",
    "Path Maiden",
    "Pelegox Cube",
    "Petitioner",
    "Phalanx Formation",
    "Plague Zombie",
    "Planar Terra-Cotta Squadron",
    "Priest of Kabriri",
    "Provincial Jiang-Shi",
    "Quatoid",
    "Rancorous Priesthood",
    "Ravener Husk",
    "Ravener",
    "Runecarved Lich",
    "Ruzadoya's Chosen",
    "Saltborn Stalkers",
    "Shadow",
    "Shadowbound Monk Statue",
    "Shambler Troop",
    "Simple Harrowkin",
    "Shock Zombie",
    "Sinspawn",
    "Skeletal Champion",
    "Skeletal Giant",
    "Skeletal Horse",
    "Skeletal Hulk",
    "Skeletal Mage",
    "Skeletal Soldier",
    "Skeletal Titan",
    "Skeleton Guard",
    "Skeleton Infantry",
    "Sniper",
    "Sootsoldiers",
    "Soul Swarm",
    "Spellskein",
    "Spring-Heeled Jack",
    "Standard Bearer",
    "Stone Bulwark",
    "Stone Lion",
    "Stone Lion Cub",
    "Stone Spider",
    "Storied Harrowkin",
    "Strigoi Progenitor",
    "Sulfur Zombie",
    "Summer Hora Queen",
    "Summer Hora",
    "Sun Warrior Brigade",
    "Swamp Blight",
    "Taljjae",
    "Tar Zombie Mammoth",
    "Tar Zombie Predator",
    "Tar Zombie Snatcher",
    "Taunting Skull",
    "Tehialai-Thief-Of-Ships",
    "Terra-Cotta Garrison",
    "The Great Flood",
    "Tidal Master",
    "Tournament Combatant",
    "Tyrannosaurus Skeleton",
    "Ulgrem-Axaan",
    "Valkyrie Tempest",
    "Vampire Count",
    "Vampire Guardian",
    "Vampire Mastermind",
    "Vampire Servitor",
    "Vampire Spawn",
    "Vetalarana Emergent",
    "Vetalarana Manipulator",
    "Virulak Necromancer",
    "Virulak Villager",
    "Vrykolakas Ancient",
    "Vrykolakas Master",
    "Vrykolakas Spawn",
    "Volodmyra",
    "Waldgeist",
    "Watchmage Squadron",
    "Werebat",
    "Werebear",
    "Wereboar",
    "Werecrocodile",
    "Weremoose",
    "Wererat",
    "Wereshark",
    "Weretiger",
    "Werewolf",
    "Withered",
    "Wolf Skeleton",
    "Woodland Scouts",
    "Worm That Walks Cultist",
    "Wrath Riot",
    "Young Black Dragon",
    "Young Blue Dragon",
    "Young Brass Dragon",
    "Young Bronze Dragon",
    "Young Copper Dragon",
    "Young Forest Dragon",
    "Young Gold Dragon",
    "Young Green Dragon",
    "Young Red Dragon",
    "Young Sea Dragon",
    "Young Silver Dragon",
    "Young Sky Dragon",
    "Young Sovereign Dragon",
    "Young Underworld Dragon",
    "Young White Dragon",
    "Xulgath Ravening",
    "Zombie Brute",
    "Zombie Dragon",
    "Zombie Hulk",
    "Zombie Lord",
    "Zombie Mammoth",
    "Zombie Owlbear",
    "Zombie Shambler",
    "Zombie Snake",
]

CREATURE_IGNORE_DC_AURA = [
    "Island Oni",
    "Primal Warden of Zibik",
    "Courtesean",
    "Loan Shark",
    "Tempest Incarnate",
]

CREATURE_ATTRIBUTES = [
    "str",
    "dex",
    "con",
    "int",
    "wis",
    "cha"
]

KINGDOM_ATTRIBUTES = [
    "culture",
    "economy",
    "loyalty",
    "stability",
]

ORC_LICENSE = {
    "name": "ORC Notice",
    "type": "section",
    "sections": [
        {
            "name": "Attribution",
            "type": "section",
            "text": "This product is based on the following Licensed Material:",
            "sections": []
        },
        {
            "name": "Attributing us",
            "type": "section",
            "text": "If you use our Licensed Material in your own published works, please credit us as follows:",
            "sections": [
                {
                    "name": "Pathfinder Open Reference",
                    "type": "section",
                    "text": "© 2023 Masterwork Tools LLC, Authors: Devon Jones, Monica Jones."
                }
            ]
        },
        {
            "name": "Reserved Material",
            "type": "section",
            "text": "Reserved Material elements in this product include, but may not be limited to: [none]"
        },
        {
            "name": "Expressly Designated Licensed Material",
            "type": "section",
            "text": "The following elements are owned by the Licensor and would otherwise constitute Reserved Material and are hereby designated as Licensed Material: [None]."
        }
    ],
    "subtype": "license",
    "license": "Open RPG Creative license",
    "text": "This product is licensed under the ORC License to be held in the Library of Congress and available online at various locations including paizo.com/orclicense, azoralaw.com/orclicense, and others. All warranties are disclaimed as set forth therein."
}
